namespace NetFIM.Global
{
    class NetFIMGlobal
    {
        public static char[] Punctuations = { '.', '!', '?', ':', ',' };
        public static string ReportStart = "Dear Princess Celestia: ";
        public static string ReportEnd = "Your faithful student, ";

        public class Keywords
        {
            public static string Variable_Empty = "nothing",
            Method_Declare = "Did you know that",
            Method_Parameter = "using",
            Method_Return2 = "Then you get",
            If_Suffix = "then",
            If_End = "That's what I would do",
            Loop_End = "That's what I did",
            IncrementPrefix = "add",
            DecrementPrefix = "subtract",
            Variable_Constant = "always";
            public class Variable_Increment
            {
                public static string Start = "There was one more";
                public static string End = "got one more";
            }
            public class Variable_Decrement
            {
                public static string Start = "There was one less";
                public static string End = "got one less";
            }
            public class Arithmetic
            {
                public class Add
                {
                    public static string Prefix = "add";
                    public static string[] Infix = { "added to", "plus" };
                }
                public class Subtract
                {
                    public static string[] Prefix = { "subtract", "the difference between" };
                    public static string[] Infix = { "minus", "without" };
                }
                public class Multiply
                {
                    public static string[] Prefix = { "multiply", "the product of" };
                    public static string[] Prefix_Infix = { "by", "and" };

                    public static string[] Infix = { "multiplied with", "times" };
                }
                public class Divide
                {
                    public static string Prefix = "divide";
                    public static string[] Prefix_Infix = { "by", "and" };

                    public static string[] Infix = { "divided by" , "over" };
                }
            }
            public static string[]
                Variable_Initialization = {
                "has",
                "is",
                "like",
                "likes",
                "was"
            }, Variable_Boolean = {
                "an argument",
                "the argument",
                "the logic",
                "argument",
                "logic",
            }, Variable_BooleanArray = {
                "many arguments",
                "many logics",
                "the arguments",
                "the logics",
                "arguments",
                "logics",
            }, Variable_Number = {
                "the number",
                "a number",
                "number",
            }, Variable_NumberArray = {
                "many numbers",
                "the numbers",
                "numbers",
            }, Variable_String = {
                "a phrase",
                "a quote",
                "a sentence",
                "a word",
                "characters",
                "letters",
                "phrase",
                "quote",
                "sentence",
                "the characters",
                "the letters",
                "the phrase",
                "the quote",
                "the sentence",
                "the word",
                "word",
            }, Variable_StringArray = {
                "many phrases",
                "many quotes",
                "many sentences",
                "many words",
                "phrases",
                "quotes",
                "sentences",
                "the phrases",
                "the quotes",
                "the sentences",
                "the words",
                "words",
            }, Variable_Character = {
                "a character",
                "a letter",
                "the character",
                "the letter",
                "character",
                "letter"
            }, Boolean_True = {
                "correct",
                "right",
                "true",
                "yes"
            }, Boolean_False = {
                "false",
                "incorrect",
                "no",
                "wrong"
            }, Method_Return = {
                "to get",
                "with",
            }, Method_Write = {
                "I said",
                "I sang",
                "I wrote",
                "I remembered",
                "I would",
            }, Method_Replace = {
                "become",
                "became",
                "becomes",
                "is now",
                "now likes",
                "now like",
                "are now",
            }, If_Start = {
                "If",
                "When",
            }, If_Else = {
                "Or else",
                "Otherwise",
            }, Conditional_Equal = {
                "is equal to",
                "was equal to",
                "were equal to",
                "had",
                "has",
                "is",
                "was",
                "were",
            }, Conditional_Not = {
                "wasn't equal to",
                "isn't equal to",
                "weren't equal to",
                "hadn't",
                "had not",
                "hasn't",
                "has not",
                "isn't",
                "is not",
                "wasn't",
                "was not",
                "weren't",
                "were not",
            }, Conditional_GreaterThan = {
                "had more than",
                "has more than",
                "is greater than",
                "was greater than",
                "were greater than",
                "were more than",
                "was more than",
            }, Conditional_GreaterThanEqual = {
                "had no less than",
                "has no less than",
                "is no less than",
                "is not less than",
                "isn't less than",
                "was no less than",
                "was not less than",
                "wasn't less than",
                "were no less than",
                "were not less than",
                "weren't less than",
            }, Conditional_LessThan = {
                "had less than",
                "has less than",
                "is less than",
                "was less than",
                "were less than",
            }, Conditional_LessThanEqual = {
                "had no more than",
                "has no more than",
                "is no greater than",
                "is no more than",
                "is not greater than",
                "is not more than",
                "isn't greater than",
                "isn't more than",
                "was no greater than",
                "was no more than",
                "was not greater than",
                "was not more than",
                "wasn't greater than",
                "wasn't more than",
                "were no greater than",
                "were no more than",
                "were not greater than",
                "were not more than",
                "weren't greater than",
                "weren't more than"
            }, Loop_While = {
                "As long as",
                "While",
            };
        }

        public static string[] CompareKeywordList = {
            "had",
            "has",
            "is",
            "was",
            "were",
            "hadn't",
            "had not",
            "hasn't",
            "has not",
            "isn't",
            "is not",
            "wasn't",
            "was not",
            "weren't",
            "were not",
            "had more than",
            "has more than",
            "is greater than",
            "was greater than",
            "were greater than",
            "were more than",
            "was more than",
            "had no less than",
            "has no less than",
            "is no less than",
            "is not less than",
            "isn't less than",
            "was no less than",
            "was not less than",
            "wasn't less than",
            "were no less than",
            "were not less than",
            "weren't less than",
            "had less than",
            "has less than",
            "is less than",
            "was less than",
            "were less than",
            "had no more than",
            "has no more than",
            "is no greater than",
            "is no more than",
            "is not greater than",
            "is not more than",
            "isn't greater than",
            "isn't more than",
            "was no greater than",
            "was no more than",
            "was not greater than",
            "was not more than",
            "wasn't greater than",
            "wasn't more than",
            "were no greater than",
            "were no more than",
            "were not greater than",
            "were not more than",
            "weren't greater than",
            "weren't more than",
            "is equal to",
            "was equal to",
            "were equal to",
            "wasn't equal to",
            "isn't equal to",
            "weren't equal to",
        };

        public static string[] KeywordsList = {
            "That's what I would do",
            "That's what I did",
            "If all else fails",
            "Or else", "Otherwise",
            "On the",
            "If",
            "When",
            "In regards to",
            "Dear",
            "I learned",
            "Did you know that",
            "Your faithful student",
            "That's all about",
            "Remember when I wrote about",
            "has",
            "is",
            "like",
            "was",
            "always has",
            "always is",
            "always like",
            "always likes",
            "always was",
            "and",
            "using",
            "I did this while",
            "I did this as long as",
            "That's what I did",
            "Here's what I did",
            "I said",
            "I sang",
            "I wrote",
            "I asked",
            "I heard",
            "I read",
            "Then you get",
            "I remembered",
            "I would",
            "argument",
            "logic",
            "logics",
            "number",
            "character",
            "letter",
            "numbers",
            "phrases",
            "quotes",
            "sentences",
            "words",
            "phrase",
            "quote",
            "sentence",
            "word",
            "are now",
            "become",
            "became",
            "becomes",
            "is now",
            "now like",
            "now likes",
            "using",
            "to get",
            "with",
            "had",
            "has",
            "were",
            "hadn't",
            "had not",
            "hasn't",
            "has not",
            "isn't",
            "is not",
            "wasn't",
            "was not",
            "weren't",
            "were not",
            "had more than",
            "has more than",
            "is greater than",
            "was greater than",
            "were greater than",
            "were more than",
            "had no less than",
            "has no less than",
            "is no less than",
            "is not less than",
            "isn't less than",
            "was no less than",
            "was not less than",
            "wasn't less than",
            "were no less than",
            "were not less than",
            "weren't less than",
            "had less than",
            "has less than",
            "is less than",
            "was less than",
            "were less than",
            "had no more than",
            "has no more than",
            "is no greater than",
            "is no more than",
            "is not greater than",
            "is not more than",
            "isn't greater than",
            "isn't more than",
            "was no greater than",
            "was no more than",
            "was not greater than",
            "was not more than",
            "wasn't greater than",
            "wasn't more than",
            "were no greater than",
            "were no more than",
            "were not greater than",
            "were not more than",
            "weren't greater than",
            "weren't more than",
            "is equal to",
            "was equal to",
            "were equal to",
            "wasn't equal to",
            "isn't equal to",
            "weren't equal to",
            "As long as",
            "While",
            "There was one more",
            "got one more",
            "got one less",
            "There was one less",
            "add",
            "added to",
            "plus",
            "subtract",
            "the difference between",
            "minus",
            "without",
            "multiply",
            "the product of",
            "by",
            "and",
            "multiply with",
            "times",
            "divide",
            "divided by",
            "over",
        };
    }
}
